### ISSUE TITLE
random_noise function

### ISSUE THREAD

**Issue by Chi-Mz** [zhenglab/TransCNN-HAE#2]
hello author, where is the random_noise() function in src/utils.py

**Comment by Haoru** [comment]
The random_noise() function comes from the util module in the skimage library, and  I have added "from skimage import util" to the src/utils.py file.

**Comment by Chi-Mz** [comment]
> The random_noise() function comes from the util module in the skimage library, and I have added "from skimage import util" to the src/utils.py file.

Thanks a lot !
