### ISSUE TITLE
How many epochs did u train in your experiments?

### ISSUE THREAD

**Issue by LaijinMeng** [zhenglab/TransCNN-HAE#3]
In your config.yml, all of the iterations in each dataset are set 700000. After training 700000 iterations (about 104 epochs),  it seems that the generated image is similar to the original polluted image?

**Comment by Haoru** [comment]
Our model has only been trained on 700,000 iterations, or about 50 epochs, on all datasets except ImageNet and Places2, two large datasets.

**Comment by Haoru** [comment]
Except for ImageNet and Places2, our model has trained on other datasets for about 70 iterations until complete convergence, and has gone through about 50 epochs.  May I ask which dataset you trained on?   Could you please give some detailed information and samples so as to analyze why the generated images seem to be similar to the original polluted images?

**Comment by Haoru** [comment]
In addition to ImageNet and Places2, our model trained on other datasets for about 70w iterations until achieving complete convergence (config.yml will be updated later). May I ask which dataset you used for training?  Could you provide more detailed training information and examples of results for us to analyze why the situation you described occurs?

**Comment by Haoru** [comment]
In addition to ImageNet and Places2, our model trained on other datasets for about 70w iterations until achieving complete convergence (config.yml will be updated later).  May I ask which dataset you used for training?  Could you provide more detailed training information and examples of results for us to analyze why the situation you described occurs?

**Comment by LaijinMeng** [comment]
I used CelebA dataset, and select 27000 images for training dataset, the train_noise.flist is ImageNet 2012. I used flist.py in ./scripts to generate train.flist and train_noise.flist. The sample in 700000 iters during training is attached. 
![700000](https://github.com/zhenglab/TransCNN-HAE/assets/53005927/e36e473c-1293-4d30-89c2-81050359338e)
It seems that the output is very similar to the input.

**Comment by Haoru** [comment]
Your output and input look exactly the same, which is very abnormal, and don't seem to go through the network. Have you observed any decrease in losses during the training process? Additionally, could you confirm if the training process was normal and if the results were accurately saved?

**Comment by LaijinMeng** [comment]
Thanks for your reply. I used the updated code, and it seems that the output started to change. I will see if there are any problems after I finish training.
